{
    "name": "Website Theme Preview Tests",
    "version": "1.0",
    "category": "Hidden",
    "sequence": 9877,
    "summary": "Create a preview website for each theme declared by this test module",
    "description": "The installation hook creates a website for each theme in this module's dependencies and applies that theme to it. Supplies website switching controls and tests for theme loading, upgrades and page templates.",
    "author": "Odoo S.A.",
    "license": "LGPL-3",
    "depends": [
        "theme_default",
        "theme_anelusia",
        "theme_artists",
        "theme_avantgarde",
        "theme_aviato",
        "theme_beauty",
        "theme_bewise",
        "theme_bistro",
        "theme_bookstore",
        "theme_buzzy",
        "theme_clean",
        "theme_cobalt",
        "theme_enark",
        "theme_graphene",
        "theme_kea",
        "theme_kiddo",
        "theme_loftspace",
        "theme_monglia",
        "theme_nano",
        "theme_notes",
        "theme_odoo_experts",
        "theme_orchid",
        "theme_paptic",
        "theme_real_estate",
        "theme_treehouse",
        "theme_vehicle",
        "theme_yes",
        "theme_zap",
    ],
    "assets": {
        "website.assets_editor": [
            "test_themes/static/src/systray_items/*",
        ],
    },
    "post_init_hook": "post_init_hook",
}
